### ISSUE TITLE
Model validation GitHub action will not work with PR changes if PR is from any fork 

### ISSUE THREAD

**Issue by richaashara** [eclipse-tractusx/sldt-semantic-models#188]
Hello Team,

1. In Governance.yml file there is a step for model validation action. in its JS file there is a step to validate model file using below command.
      **bamm aspect <<model_file_name>> validate**
This can only work if the check out repo contains the model file. But, in-case of PR, repository folder will not have the model file, So, won't it  fail in all case?

**Comment by bs-jokri** [comment]
Hi @richaashara, 
thanks for reaching out. As a GitHub action is ran in the context of the branch it is contained in, the validation action should work also for PRs.
you can see this eg in 
https://github.com/eclipse-tractusx/sldt-semantic-models/pull/204
where the validation is running in a pr.

however, what is still under construction is the move to SAMM. For that we have a PR, which also needs to update the CLI used in order to support also SAMM.

https://github.com/eclipse-tractusx/sldt-semantic-models/pull/215

HTH
Johannes

**Comment by bs-jokri** [comment]
@richaashara does my comment resolve your issue? If so, can we close?

**Comment by richaashara** [comment]
yes. @bs-jokri. We can close this issue.
